# -*- coding: utf-8 -*-
"""projeto de calculadora py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTRTizdvRmKlQTTfzIX04HAFDo_0gXVM

#meu primeiro projeto.
"""

num1=float(input("digite o primeiro numero:"))
num2=float(input("digite o segundo numero:"))

print("soma:", num1+num2)
print("subtração",num1-num2)
print("multiplicação",num1*num2)

if num2 <=0:
  print("divisão", num1/num2)

else:
     print("não é possivel dividir por zero.")